spring:
  application:
    name: market-api
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:local}

datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}