spring:
  application:
    name: market-api
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: info

jwt:
  secret: ${JWT_SECRET}
  exp-ms: 3600000

server:
  tomcat.apr.enabled: false